### ISSUE TITLE
pip install not working, does not install py files

### ISSUE THREAD

**Issue by TurboCooler** [harshnative/pysqlitecipher#1]
pip install only installs the following:

pysqlitecipher-0.21.dist-info

- INSTALLER
- LICENSE
- LICENSE.txt
- METADATA
- RECORD
- REQUESTED
- top_level.txt
- WHEEL

There is no source directory thus you cannot do an import of the module

it is missing a pysqlitecipher folder

**Comment by harshnative** [comment]
> pip install only installs the following:
> 
> pysqlitecipher-0.21.dist-info
> 
> * INSTALLER
> * LICENSE
> * LICENSE.txt
> * METADATA
> * RECORD
> * REQUESTED
> * top_level.txt
> * WHEEL
> 
> There is no source directory thus you cannot do an import of the module
> 
> it is missing a pysqlitecipher folder



Fixed with version 0.22

pip install pysqlitecipher==0.22

Documentation - 
https://www.blog.letscodeofficial.com/@harshnative/encrypting-sqlite-database-in-python-using-pysqlitecipher-module-easy-and-secure-encryption-in-python-sqlite/
