### ISSUE TITLE
Add Column

### ISSUE THREAD

**Issue by ghost** [harshnative/pysqlitecipher#2]
hi
i need add column into table
How can I do that?

**Comment by harshnative** [comment]
currently you need to get table data and make a new table

but version 2 of the module is in progress and will be available soon :)

**Comment by ghost** [comment]
WoWI'm looking forward to it waiting for the update :)Generally 1.update of table columns and 2.delete tablei have these on my mind right now  Thank you,   Windows için Posta ile gönderildi Kimden: harsh guptaGönderilme: 3 Aralık 2021 Cuma 15:00Kime: harshnative/pysqlitecipherBilgi: sirdash; AuthorKonu: Re: [harshnative/pysqlitecipher] Add Column (Issue #2) currently you need to get table data and make a new tablebut version 2 of the module is in progress and will be available soon :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
